server:
  port: 10185
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: DigitalServices
  data:
    mongodb:
      uri: mongodb://localhost:27017/applications
  kafka:
    bootstrap-servers: praveensmacbook:9092 #check if you are running local it will display in kafka startup logs
    topic:
      dgs-applicationRegistration: REG-application-created
      dgs-applicationRegistrationUpate: REG-application-Updated
    consumer:
      group-id: cloudMs
      auto-offset-reset: earliest
management:
  endpoints:
    web:
      exposure:
        include: '*'
logging:
  level:
    root: INFO